#cloudbuild.yaml
steps:
- name: 'docker/compose:1.23.2'
  args: ['up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'logsone:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/[PROJECT-ID]/[IMAGE]"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --image=gcr.io/[PROJECT-ID]/[IMAGE]:[TAG]
  - --location=[LOCATION]
  - --cluster=[CLUSTER]
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

