#cloudbuild.yaml
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/logsone', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/logsone"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - run
  - --image=gcr.io/$PROJECT_ID/logsone
  - --location=us-west2-a
  - --cluster=logsone-cluster
  - 'DATABASE=$$DATABASE'
  - 'USERDB=$$USERDB'
  - 'PASSWORDDB=$$PASSWORDDB'
  - 'PORT=$$PORT'

images:
- 'gcr.io/$PROJECT_ID/logsone'
